Regular:
  prefix: '@'
  titles:
    enabled: true
    title: '&a%player%'
    subtitle: '&dhas mentioned &byou!'
  actionbar:
    enabled: true
    text: '&a%player% &dhas mentioned &byou!'
  particles:
    enabled: true
    particle-type: DRIP_WATER
  sound: LEVEL_UP
  cooldown:
    enabled: true
    time: 5
  replacement:
    enabled: true
    text: '&a@&l%player%&r'
  message:
    enabled: true
    text: '&a%player% &dhas mentioned &byou!'
Everyone:
  prefix: '@'
  titles:
    enabled: true
    title: '&a%player%'
    subtitle: '&dhas mentioned &beveryone!'
  actionbar:
    enabled: true
    text: '&a%player% &dhas mentioned &beveryone!'
  particles:
    enabled: true
    particle-type: DRIP_WATER
  sound: LEVEL_UP
  cooldown:
    enabled: true
    time: 5
  replacement:
    enabled: true
    text: '&a@everyone&r'
  message:
    enabled: true
    text: '&a%player% &dhas mentioned &beveryone!'
useOldWay: true
needPermissionToMention: false
needsPrefix: true
hooks:
  Essentials: true
  FactionChat: true
  mcMMO: true
  SuperVanish: true